image: node

stages:
  - test
  - build
  - deploy

before_script:
  - yarn

lint: 
  stage: test
  script:
    - yarn lint

unit-tests:
  stage: test
  script:
    - yarn test:unit

integration-tests:
  stage: test
  image: cypress/base:8
  script:
    - yarn test:e2eheadless
  artifacts:
    paths: 
      - tests/e2e/videos

build:
  stage: build
  script:
    - yarn build
  artifacts:
    paths:
      - dist

deploy:
  stage: deploy
  script:
    - yarn deploy
  dependencies: 
    - build