image: node

before_script:
  - yarn

lint: 
  script:
    - yarn lint

unit-tests:
  script:
    - yarn test:unit

integration-tests:
  image: cypress/base:8
  script:
    - yarn test:e2eheadless
  artifacts:
    paths: 
      - tests/e2e/videos